---
output:
  #bookdown::html_document2: default
  #bookdown::word_document2: default
  bookdown::pdf_document2:
    template: templates/template.tex
    keep_tex: true
documentclass: book
#bibliography: [bibliography/references.bib, bibliography/additional-references.bib]
---

# Discussion
\minitoc <!-- this will include a mini table of contents-->

Let us take a look at a few limitations of this work, how it compares to 
the primary research works, and then discuss the future avenues yet to be explored.

### Limitations{-}

The prototype does not implement whole program path generation, and simply keeps
a rolling hash of the CFlog. Adding that part may increase the total runtime. We
should note though, that report generation is not a part of the regular program
and can be considered a separate operation. The benchmark results still include the
time spent in the TA for the wrap up, just to give an idea about the overheads
added as a whole to the process.

The logging on violation part, although mentioned in design has not been implemented yet 
in the prototype. We rely on the default fault handler to kill the process on encountering
an illegal instruction. The actual handling can also be implementation dependent 
and users may choose to recover the execution state instead of killing the process,
or to simply log and send a report to Vrf.

Some of the assumptions like `W` $\oplus$ `X` are not foolproof and there are 
proof of concepts exploiting them. We need to decrease the trusted conputing base and the
assumptions to increase the security guarantees given by this work.

We also could not add CFI measures other than PAC and BTI. Other software or 
hardware features can be added on top of this to see how they provide security or performance gains.
MTE was considered, but excluded due to the current state of adoption for these 
features. Many devices claim to conform to the spec, while skipping on the mandatory features for them.
Case in point, Apple M1. It claims to be a ARMv8.5-A chip, while not implementing `FEAT_BTI`.

PAC is only enabled if the whole dependency chain also has it enabled. That is, if
a shared library does not support PAC, it is disabled for the whole program.
This is specially true for the compiler toolchains. The archive
files (`libpthread.a` for example) compiler links against should have these
features enabled for them to be enabled in the final binary. Clang just gives out a
warning about the feature flag being unused, which may get buried in the compilation logs.
So we cannot use PAC with pre-compiled binaries that do not have it enabled.

The benchmarking was done on a simulated Aarch64 CPU inside QEMU instead of a 
hardware board. Thus we have only taken the ratio of baseline code and the 
instrumented code. The timings may differ a bit on a physical board.

---

When there is a change in the threat model where the attacker may prioritize
attack results over invisibility, CFA mechanisms seem to fall short while CFI fits the
role perfectly. Not much research has been done to bring these two facets together,
and to see how they could both complement each other [@sok].

CFA+ tries to bridge the gap between CFI and CFA, but it makes attacks a bit harder,
but not impossible to perform due to the design issues discussed in section
[1.3.2 CFA+ Limitations](#cfaplus-limitations).

Our work gives security guarantees while also giving a choice for Fine to Coarse-grained
logging for attestation. Our `Violation` loglevel is equivalent to CFA+, 
while also being secure due to its dynamic nature of pointer authentication.
And therefore the instrumentation is not vulnerable to static checks and symbolic execution.

As we go for more verbose log levels, it gets easier to detect attacks and stop
them as they happen. The TA can be configured to monitor the logs continuously 
and stop the execution as soon as it detects something anomolous.

Talking about loglevels, as seen in the results, adding integrity features on top
of BLAST had a low effect on performance. This means that the `Full` loglevel
can be used as is, while changing to `Optimised` could give a performance boost over it.
We also preserve guarantees given by BLAST, and just add more on top of them.

Note that the concepts used are portable, and any alternative feature that gives
similar guarantees can be used. So even though flawed PAC or BTI implementations
would affect the security of the binary, they can be replaced by other similar methods.
This is also true for the target ISA. These concepts - as with BLAST - can be ported
over to other architectures if similar features are present. These concepts can also
be used to complement other CFA and CFI techniques to gain performance and integrity guarantees.

Our *current prototype's* security is dependent on the ARM hardware and not in the software.
And any flaws (if present) can be rectified in implementation design. Although this makes
vulnerabilities harder to fix for already deployed systems, the design gets better 
with time and secure on future devices.

<!-- ### Future Research{-} -->

The idea behind this work was that if the Vrf has the expected control flow, why
not share it with the RoT on the Prv, which would be able to prevent anomalies
immediately instead of reporting the damage later on.
The goal would then be to add modifications to the TEE which would get the expected
control flow along with the input, monitor the program execution, and take action 
if the integrity has been violated. This was an experiment towards that goal, and we can
pursue this further by modifying CFLAT/OAT monitors to provide this functionality.
If it succeeds, that solution can be used in critical-systems where it could
guarantee that either the program ran "correctly", or it did not run at all.

One area that can also provide further insipiration is the Digital Rights Management
(DRM) scene. Especially the software and game DRM categories. The work done there
is similar, where the binaries have integrity checks for all program files, and
some kind of attestation where program states are sent over to remote servers
for various reasons like licensing and anti-cheat. This may be hard to do as most
research in that area is classified to keep it from being bypassed.

While CFI is popular in security community and industry alike, CFA has many areas
left to be researched upon. Compiler optimisations support specially for CFA,
instrumentation compatibility, CFA for complex programs, and attestation evidence
storage optimisation are some of the open problems worth looking into.
Ammar et al.[@sok] go into more detail on current state of things and open problems
waiting to be solved.
